version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql-data:

  app:
    build: . # Dockerfile para seu sistema
    restart: always
    ports:
      - "5289:5289" # Porta que seu sistema está exposto
    depends_on:
      - mysql
